name: TsubusabaUtils
version: '1.0.0'
main: net.tsubu.tsubusabautils.TsubusabaUtils
api-version: '1.21'
author: Tsubu
description: Integrated plugin with Jobs rewards system and SendMoney functionality

commands:
  sendmoney:
    description: Open the send money GUI
    usage: /sendmoney
    aliases: [sm]
  returndeath:
    description: 死亡地点に戻る
    usage: /returndeath
    aliases: [rd, back]
  thome:
    description: Open home GUI
    usage: /thome
  gmenu:
    description: Open GPMenu GUI
    usage: /gmenu
  rec:
    description: Open Recipe GUI
    usage: /rec
    aliases: recipe
  res:
    description: 資源ワールド移動
    usage: /res
    aliases: resource
  main:
    description: メインワールド移動
    usage: /main
  spawn:
    description: 現在のワールドのスポーン地点にテレポート
    usage: /spawn
  wiki:
    description: つぶ鯖のガイドwikiを開く
    usage: /wiki

  adminsell:
    description: Open AdminSell GUI
    usage: /<command> [category|reload]
    permission: tsubusabautils.adminsell
    permission-message: You don't have permission.

permissions:
  sendmoney.use:
    description: Allows use of the sendmoney command
    default: true
  sendmoney.admin:
    description: Administrative permissions for SendMoney
    default: op
  tsubusabautils.adminsell:
    description: Use /adminsell
    default: true
  tsubusabautils.adminsell.reload:
    description: Reload all adminsell configs
    default: op